# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 10
  - name: Overview
    parent: Tools
    url: tools
    weight: 20
  - name: Obsarray
    parent: Tools
    url: tools/obsarray/
    weight: 21
  - name: Punpy
    parent: Tools
    url: tools/punpy/
    weight: 22
  - name: Comet_math
    parent: Tools
    url: tools/comet_math/
    weight: 23
  - name: Examples
    url: examples
    weight: 29
  - name: News
    url: post
    weight: 30
  - name: People
    url: people
    weight: 40
#  - name: Publications
#    url: publication
#    weight: 50
  - name: Contact
    url: contact
    weight: 60
